# Generated by Django 3.2.8 on 2021-10-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedetails',
            name='logo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
