# Generated by Django 3.2.8 on 2021-10-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0002_alter_sitedetails_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteDetails',
            new_name='SiteDetail',
        ),
    ]
